### PR TITLE
Footer with timestamp for the generated markdown

### PR DESCRIPTION
**Pull request by itssiva24**
## Description

Added a footer with the timestamp for the generated markdown. I modified the tests for the same. It involves changing the current system clock when the tests are running. Other possible methods involved using a dependency or changing the global "Date". Changing the global, yielded undesirable results. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

Issue #9 

## Motivation and Context

It help keep track of the latest generated time of the markdown.

## How Has This Been Tested?

1.  First, I added the footer to snapshots with the timestamp 2021-12-13T18:30:00.000Z (This can be any valid ISO string).
2.  Then set Jest to use "modern" fakeTimers and setting the system time to _new Date(2021, 11, 14)_ (This is to mock the date we set in snapshots).
3.  Doing this did not affect other areas of the code involving Date constructor(with arguments) or it's methods(UTC, now, parse).

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Review by lirantal — APPROVED** [review]

**Comment by lirantal** [comment]
This looks great @itssiva24 👏

**Comment by lirantal** [comment]
@itssiva24 can you take a look at the failing tests? 

From the CI:
image

**Comment by itssiva24** [comment]
> @itssiva24 can you take a look at the failing tests?
> 
> From the CI: image

Yes, sure.

**Comment by lirantal** [comment]
Looks good now!

**Pull request merged**
